### ISSUE TITLE
Build slugs for legacy data

### ISSUE THREAD

**Issue by janlimpens** [mongoid/mongoid-slug#174]
Hello, I am trying to add slugs to objects created before the inclusion of your lib. But somehow, some objects refuse to create slugs... See here:
https://stackoverflow.com/questions/25753601/how-to-sluggify-legacy-data-with-mongoidslug
Any help would be very much appreciated :)

**Comment by anuja-joshi** [comment]
@digitalplaywright what if we provide one rake task that will take model name(optional) and will build slug for all objects of that model or just objects for which slug is blank? because I come under same situation and I manually had to write a task do same

**Comment by digitalplaywright** [comment]
@anuja-joshi That would be great. You might find some inspiration on the migration tasks here https://github.com/digitalplaywright/mongoid-slug/wiki/How-to-upgrade-to-1.0.0-or-newer

**Comment by anuja-joshi** [comment]
@digitalplaywright :+1:  ... will send PR for this
