### ISSUE TITLE
Mongoid 6 beta support

### ISSUE THREAD

**Issue by narutosanjiv** [mongoid/mongoid-slug#230]
Currently Rails 5 work with mongoid 6-beta, and this gem does not seem to be compatible with mongoid-6-beta

**Comment by sivagollapalli** [comment]
@narutosanjiv I think it supports as travis build is passing against `mongoid` HEAD. Could you please check https://travis-ci.org/mongoid/mongoid-slug/builds/159180594 . Let me know if I missing anything.

**Comment by narutosanjiv** [comment]
@sivagollapalli My bad, it seem that there are issue from my side, my app requirement is different which does not fit for above issue, closing issue for now.

**Comment by dblock** [comment]
There's also a 6.0.0.rc0 out there, I'd appreciate a PR that explicitly adds it into the test pool.
