### ISSUE TITLE
[Rails 5 Deprecation] alias_method_chain is deprecated

### ISSUE THREAD

**Issue by Soulou** [mongoid/mongoid-slug#232]
The method is used there:

https://github.com/mongoid/mongoid-slug/blob/46b5f5e1e8f917c8975ddd1339ed21eb48c2f4eb/lib/mongoid/slug/paranoia.rb#L16

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at [path]/config/environment.rb:5)
```

and is now deprecated. Interesting link about that: http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

**Comment by dblock** [comment]
Yes, would love a PR fixing this. Thanks.
