### ISSUE TITLE
Rake task not working

### ISSUE THREAD

**Issue by Loschcode** [mongoid/mongoid-slug#245]
I installed the gem and added `slug :name` to my model `Shop` to try it out. There are already entries in the database so I decided to launch `rake mongoid_slug:set`

The following occurs ...

```
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/tasks/mongoid_slug.rake:7: warning: constant ::TimeoutError is deprecated
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 2)
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/bson-4.1.1/lib/bson/regexp.rb:144:in `initialize'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug/unique_slug.rb:133:in `new'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug/unique_slug.rb:133:in `regex_for_slug'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug/unique_slug.rb:90:in `block in find_unique'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug/unique_slug.rb:80:in `synchronize'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug/unique_slug.rb:80:in `find_unique'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug.rb:261:in `find_unique_slug'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug.rb:209:in `apply_slug'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug.rb:203:in `build_slug'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/mongoid/slug.rb:231:in `set_slug!'
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/tasks/mongoid_slug.rake:15:in `block (4 levels) in <top (required)>'```

**Comment by anuja-joshi** [comment]
@Loschcode  this is happening because of `BSON::Regexp::Raw.new(escaped_pattern)` at line https://github.com/mongoid/mongoid-slug/blob/master/lib/mongoid/slug/unique_slug.rb#L133
If you have old `bson` version it does not have default option parameter so "initialize" is throwing argument error. Default option parameter support is added to bson - v4.2.1

**Comment by Loschcode** [comment]
How can I fix that ? Should I upgrade MongoID ?

**Comment by dblock** [comment]
It does look like a bug, as we support mongoid 3-whatever, so I'd appreciate a spec and a fix, please.

**Comment by Loschcode** [comment]
is there any solution ? I'm waiting for a fix to include it within my project ... Maybe I could help but I don't know the codebase at all.

**Comment by dblock** [comment]
What version of mongoid-slug are you using? I believe 5.3.3 fixes your problem, can you please confirm?

**Comment by Loschcode** [comment]
I'm currently using `mongoid-slug (5.3.3)` which seems to be the latest one

**Comment by dblock** [comment]
And which version of mongoid?

If you look at https://github.com/mongoid/mongoid-slug/blob/master/lib/mongoid/slug/unique_slug.rb#L133, with Mongoid 3 and 4 you should not hit that code.

**Comment by Loschcode** [comment]
The version I see in the `Gemfile.lock` is `mongoid (5.0.2)` is that fine ?

**Comment by dblock** [comment]
I was confused. Just try to upgrade bson-4.1.1 to bson-4.2.1, `bundle update bson`?

**Comment by Loschcode** [comment]
I updated BSON such as `Installing bson 4.2.2 (was 4.1.1)` and it now has a different error

```$ rake mongoid_slug:set
/Users/loschcode/.rvm/gems/ruby-2.3.3/gems/mongoid-slug-5.3.3/lib/tasks/mongoid_slug.rake:7: warning: constant ::TimeoutError is deprecate```

What should I do next ?

**Comment by dblock** [comment]
That's a warning, not an error. It worked no?

**Comment by Loschcode** [comment]
It seems to work, I guess it's the end of the issue then

**Comment by dblock** [comment]
Maybe that task should log something :) Feel free to contribute!

**Comment by alaouy** [comment]
I ran to the same issue, I confirm that upgrading bson to `v4.2.2` actually fixed the problem.
