### ISSUE TITLE
TypeError: compared with non class module

### ISSUE THREAD

**Issue by chandanbenjaram** [mongoid/mongoid-slug#247]
After an upgrading to Ruby2.3.4, Rails5.1.3, mongoid 6.2.0, we are seeing issues popping up from 'mongoid-slug', '~> 5.3.3'

Here are additional details:
https://gist.github.com/chandanbenjaram/abb3e96ce8fbc5358996f0c62a68a3bd

**Comment by chandanbenjaram** [comment]
Hello, anyone?

**Comment by dblock** [comment]
Looks like a bug to me. The error you're getting is `TypeError: compared with non class module` from [here](https://github.com/mongoid/mongoid-slug/blob/master/lib/tasks/mongoid_slug.rake#L7). Figure out what value it's trying to convert here and then try to turn this into a spec?

**Comment by syzspectroom** [comment]
recently faced this issue. here is my proposed fix: #251
