### ISSUE TITLE
Add support for mongoid 7

### ISSUE THREAD

**Issue by Fudoshiki** [mongoid/mongoid-slug#249]
@dblock, I have some points to discuss

- [ ] add support for **mongoid 7.x**
- [ ] add support for `mongoid-paranoid`
- [ ] https://github.com/mongoid/mongoid-slug/issues/236

Source https://github.com/Fudoshiki/mongoid-slug
I can update to **mongoid 7** stable and open PR

**Comment by dblock** [comment]
We don't want to break compatibility with older versions of mongoid, would take any PR that adds support for 7 that doesn't remove support for older versions.

**Comment by Fudoshiki** [comment]
updated

**Comment by dblock** [comment]
@Fudoshiki Please make PRs

**Comment by dblock** [comment]
[Donate $50 to my charity](https://runwithtfk.org/Profile/PublicPage/61018) and I can take care of this.

**Comment by dblock** [comment]
My offer still stands :)

**Comment by dblock** [comment]
What, nobody cares about the children? FYI I just did this for mongoid-history in https://github.com/mongoid/mongoid-history/issues/220

**Comment by kailan** [comment]
Compatibility added in #252.

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid-slug/pull/252#issuecomment-413296446
