### ISSUE TITLE
Can't get the gem to work

### ISSUE THREAD

**Issue by vfonic** [mongoid/mongoid-slug#256]
Hi,

Thanks for the great gem! ❤️ 

I have this situation: I made a little gem that has these dependencies:
```rb
s.add_dependency 'mongoid', '~> 6.0.3'
s.add_dependency 'mongoid-slug'
```

The gem is used in couple of other projects and includes all the mongo models we use across those projects.

To make it more interesting, several models within this gem need to have slug field.

I've created this concern that will is included in all of those models:
```rb
module SlugFields
  extend ActiveSupport::Concern

  included do
    include Mongoid::Slug
    # field :slug
    slug do |cur_object|
      (cur_object[:name] || cur_object[:title]).to_url
    end
  end
end
```

This doesn't work. If I add debugger breakpoint inside the `slug do...` block, it doesn't hit it. I also tried with `slug :title do...` (but that's incorrect in my case, as some models have `:name`, while others use `:title` field.

What am I missing?

I'm willing to contribute to the Readme, but I first need to make it work to do so.

Also, I'd like to be able to create a slug from multiple fields, in case there's a db collision. (I couldn't find much information regarding avoiding collisions in the readme, just the block mentioning slug checking during autocomplete)

Ideally, I'd call that field `slug` in the database, as we have a node.js app using the same database and it's using `slug` field when creating/reading slugs from records. We already have records with slugs, this is just an addition.

Thanks!

**Comment by vfonic** [comment]
I got it to work.

What's not working, and I didn't know that, is that you can't do:

```ruby
event = Event.new({ title: 'New title' })
event.slug
```

You'll get something that looks like (potential future) event mongo ID.

I think friendly_id had this working so I assumed this gem works the same way.

I'm not sure there's much to be added regarding this issue to the README. @dblock  Should I submit a PR with a sentence mentioning that slug is generated only on save?

Is there any way to customize the db field? I'd like to use `slug` string field instead of `_slugs` array.

**Comment by dblock** [comment]
I am confused by what's going on above. Is the problem just that trying to access the slug on an unsaved model doesn't give you the slug value? That would be worth documenting. I also think that we should be probably raising an exception trying to access the slug on an unsaved model, so maybe open a feature request?

Customizing the db field seems unrelated. I am pretty sure we don't support a custom name, but would like to. Same re: feature request/PR.

**Comment by vfonic** [comment]
I'm pretty sure this is the line of code that returns the `id` of unsaved record: https://github.com/mongoid/mongoid-slug/blob/master/lib/mongoid/slug.rb#L252

I heavily modified the library to store the slug in `slug` field in the database, so it works for my use-case, but the code changes I made are definitely not PR ready for this gem/repo.

I'll close this issue as it's resolved. Thank you!
I won't be working on adding mentioned features as I'll be using my messy modified version of the gem. It's only a temporary (which never is) solution for a quick project I'm working on.

Thank you!

**Comment by dblock** [comment]
Thanks @vfonic. Be aware that the library stores an array of slugs, not a single slug and a lot of care went into ensuring many scenarios work.

**Comment by vfonic** [comment]
Absolutely. I broke the whole test suite and it's really a slippery ground.
I hope it works within the project I'm working on.

Thanks!
