### ISSUE TITLE
Can't find document by localized slug

### ISSUE THREAD

**Issue by stefankp** [mongoid/mongoid-slug#258]
Looking up a document by localized slug returns `nil`, looking it up by the default language works. Below is my setup.

Model:
```ruby
class Foo
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String, localize: true
  slug :title, localize: true
end
```

Data:
```
Foo: {
  title: {"en"=>"Hello World", "de"=>"Hallo Welt"},
  _slugs: {"en"=>["hello-world"], "de"=>["hallo-welt"]},
}
```

Finding by default locale works:
```
Foo.find('hello-world')
=> #<Foo ...>
```

Finding by other locale returns nil:
```
Foo.find('hallo-welt')
=> nil
```

Am I missing some configuration? Does the `I18n.locale` have to be changed every time before the lookup for a localized string?

**Comment by stefankp** [comment]
Correct. If that is intentional , then we can close this. 

Feature wise changing this might make sense though.

**Comment by dblock** [comment]
Let's leave this open as a feature request. Maybe you can double-check that we have clear specs that describe current behavior and PR changes of how you think it should work?
